name: Deploy a Django app to App Service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: python3 -m pip install --upgrade pip
    - run: python3 --version
    - run: python --version
    - run: pip3 --version

    - name: Install modules and zip the project files
      run: |
       pip3 install -r requirements.txt
       zip -r myapp.zip 

    # Finally, deploy the app to App Service
    - uses: azure/appservice-actions/webapp@master
      with:
        app-name: pythonignite2019
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './myapp.zip'
