name: Deploy a Django app to App Service

on: push

jobs:
  build-n-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Set Python version (https://github.com/actions/setup-python)
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.x' 
        architecture: 'x64'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v1
      with:
        platform: python

    # Finally, deploy the app to App Service (https://github.com/Azure/webapps-deploy)
    - uses: azure/webapps-deploy@v1
      with:
        app-name: freebergPythonOryx
        publish-profile: ${{ secrets.PUB_PROF_ORYX_ACTION }}
