name: Deploy a Django app to App Service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #- run: yes | sudo apt install python3.7
    #- run: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
    #- run: python3 -m pip install --upgrade pip
    #- run: python3 --version
    #- run: python --version

    # https://github.com/actions/setup-python
    - uses: actions/setup-python@v1
      with:
      python-version: '3.7.4' # Version range or exact version of a Python version to use, using semvers version range syntax.
      architecture: 'x64' # (x64 or x86)

    - name: Install modules and zip the project files
      run: |
       python3 -m pip install -r requirements.txt
       zip -r myapp.zip 

    # Finally, deploy the app to App Service
    - uses: azure/appservice-actions/webapp@master
      with:
        app-name: pythonignite2019
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: './myapp.zip'